apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wahm-allam-539948
  namespace: aiea-interns
  labels:
    app.kubernetes.io/name: wahm
    wahm/stage: allam-generation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: rook-ceph-block
